FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    gcc \
    build-essential \
    libxerces-c-dev \
    libmysqlclient-dev \
    liblua5.1-dev \
    xutils-dev \
    psmisc
	
RUN mkdir /home/darkeden
RUN mkdir /home/darkeden/vs
RUN mkdir /home/darkeden/vs/src

WORKDIR /home/darkeden/vs/src