#!/bin/sh
vi AR.h Belt.h Blade.h Bracelet.h Coat.h Cross.h Glove.h Helm.h Mace.h Necklace.h Ring.h SG.h SMG.h SR.h Shield.h Shoes.h Sword.h Trouser.h VampireCoat.h VampireBracelet.h VampireEarring.h VampireNecklace.h VampireRing.h VampireWeapon.h VampireAmulet.h
