#!/bin/csh -f

set SrcFiles=`ls *.h *.cpp`
set SrcDir='GS LS SS'

foreach Dir ($SrcDir)
	mkdir $Dir >& /dev/null
	rm -f $Dir/Makefile >& /dev/null
	cp Makefile.$Dir $Dir/Makefile
	echo -n "refresh "$Dir": "
	cd $Dir

#	rm -f *.h *.cpp *.o

	foreach File ($SrcFiles)
		ln -s ../$File $File >& /dev/null
		echo -n .
	end

	echo ''

	cd ..
end

